name: Build, Scan and Push

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/test-inputs-if.yml@main
    with:
      enable_scan: true
