name: Build, Scan and Push

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/test-minimal-docker.yml@main
    with:
      image_name: docker-stunnel
    secrets: inherit
