name: Build, Scan and Push

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/test-reusable.yml@main
    with:
      message: "test from docker-stunnel"
