name: CI

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/docker-ci.yml@bc67bfd693eafaf8371ae6ba2626e1f977ab3311 # main
    with:
      image_name: docker-stunnel
      enable_release_drafter: true
    secrets: inherit

  auto-release:
    if: github.event_name == 'schedule'
    needs: [docker]
    uses: mbologna/.github/.github/workflows/auto-release.yml@bc67bfd693eafaf8371ae6ba2626e1f977ab3311 # main
    with:
      strategy: docker
      image: docker.io/mbologna/docker-stunnel
    secrets: inherit
