name: Build, Scan and Push

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
  security-events: write

jobs:
  docker:
    uses: mbologna/.github/.github/workflows/docker-build-scan-push.yml@52c23f956da99f55be4ae1cb41ad09953953eee7 # main
    with:
      image_name: docker-stunnel
      enable_release_drafter: true
    secrets: inherit
